package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TmDeptPO;
import cn.nesc.general.authcenter.model.TmDeptPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmDeptPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    long countByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insert(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insertSelective(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    List<TmDeptPO> selectByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    TmDeptPO selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") TmDeptPO record, @Param("example") TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExample(@Param("record") TmDeptPO record, @Param("example") TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKeySelective(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKey(TmDeptPO record);
}