package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TmRolePO;
import cn.nesc.general.authcenter.model.TmRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    long countByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insert(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insertSelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    List<TmRolePO> selectByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    TmRolePO selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExample(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKeySelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKey(TmRolePO record);
}