package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TmUserPO;
import cn.nesc.general.authcenter.model.TmUserPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmUserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    long countByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insert(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insertSelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    List<TmUserPO> selectByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    TmUserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExample(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKeySelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKey(TmUserPO record);
}