package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TrRoleFuncPO;
import cn.nesc.general.authcenter.model.TrRoleFuncPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrRoleFuncPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    long countByExample(TrRoleFuncPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int deleteByExample(TrRoleFuncPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int insert(TrRoleFuncPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int insertSelective(TrRoleFuncPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    List<TrRoleFuncPO> selectByExample(TrRoleFuncPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    TrRoleFuncPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrRoleFuncPO record, @Param("example") TrRoleFuncPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int updateByExample(@Param("record") TrRoleFuncPO record, @Param("example") TrRoleFuncPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int updateByPrimaryKeySelective(TrRoleFuncPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_func
     *
     * @mbg.generated Wed Nov 22 15:01:10 CST 2023
     */
    int updateByPrimaryKey(TrRoleFuncPO record);
}