package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TrUserRolePO;
import cn.nesc.general.authcenter.model.TrUserRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrUserRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    long countByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insert(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insertSelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    List<TrUserRolePO> selectByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    TrUserRolePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExample(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKeySelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKey(TrUserRolePO record);
}