package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TrUserPostPO;
import cn.nesc.general.authcenter.model.TrUserPostPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrUserPostPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    long countByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insert(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int insertSelective(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    List<TrUserPostPO> selectByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    TrUserPostPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrUserPostPO record, @Param("example") TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByExample(@Param("record") TrUserPostPO record, @Param("example") TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKeySelective(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    int updateByPrimaryKey(TrUserPostPO record);
}