package cn.nesc.general.authcenter.mapper;

import cn.nesc.general.authcenter.model.TrUserDeptPO;
import cn.nesc.general.authcenter.model.TrUserDeptPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrUserDeptPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    long countByExample(TrUserDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByExample(TrUserDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insert(TrUserDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int insertSelective(TrUserDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    List<TrUserDeptPO> selectByExample(TrUserDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    TrUserDeptPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrUserDeptPO record, @Param("example") TrUserDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByExample(@Param("record") TrUserDeptPO record, @Param("example") TrUserDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKeySelective(TrUserDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_dept
     *
     * @mbg.generated Mon Feb 27 16:12:16 CST 2023
     */
    int updateByPrimaryKey(TrUserDeptPO record);
}