package cn.nesc.general.authcenter.model;

import java.io.Serializable;
import java.util.Date;

public class TrRoleFuncFrontPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.role_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.menu_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tr_role_func_front
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.id
     *
     * @return the value of tr_role_func_front.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.id
     *
     * @param id the value for tr_role_func_front.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.role_id
     *
     * @return the value of tr_role_func_front.role_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.role_id
     *
     * @param roleId the value for tr_role_func_front.role_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.menu_id
     *
     * @return the value of tr_role_func_front.menu_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.menu_id
     *
     * @param menuId the value for tr_role_func_front.menu_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.create_by
     *
     * @return the value of tr_role_func_front.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.create_by
     *
     * @param createBy the value for tr_role_func_front.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.create_date
     *
     * @return the value of tr_role_func_front.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.create_date
     *
     * @param createDate the value for tr_role_func_front.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.update_by
     *
     * @return the value of tr_role_func_front.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.update_by
     *
     * @param updateBy the value for tr_role_func_front.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.update_date
     *
     * @return the value of tr_role_func_front.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.update_date
     *
     * @param updateDate the value for tr_role_func_front.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}