package cn.nesc.general.authcenter.model;

import java.io.Serializable;
import java.util.Date;

public class TrUserPostPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.user_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.post_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_post.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tr_user_post
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.id
     *
     * @return the value of tr_user_post.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.id
     *
     * @param id the value for tr_user_post.id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.user_id
     *
     * @return the value of tr_user_post.user_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.user_id
     *
     * @param userId the value for tr_user_post.user_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.post_id
     *
     * @return the value of tr_user_post.post_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.post_id
     *
     * @param postId the value for tr_user_post.post_id
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.create_by
     *
     * @return the value of tr_user_post.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.create_by
     *
     * @param createBy the value for tr_user_post.create_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.create_date
     *
     * @return the value of tr_user_post.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.create_date
     *
     * @param createDate the value for tr_user_post.create_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.update_by
     *
     * @return the value of tr_user_post.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.update_by
     *
     * @param updateBy the value for tr_user_post.update_by
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_post.update_date
     *
     * @return the value of tr_user_post.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_post.update_date
     *
     * @param updateDate the value for tr_user_post.update_date
     *
     * @mbg.generated Wed Mar 01 13:51:46 CST 2023
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}